import { invoke } from "@tauri-apps/api/core";
import { useEffect, useState } from "react";
import { SkeletonBlock } from "../components/Skeleton";

interface DigestRecord {
  id: string;
  digest_type: string;
  content: string;
  period_start: string;
  period_end: string;
  entry_count?: number;
  org?: string;
  created_at?: string;
}

interface Props {
  activeOrg: string;
}

export function ReportsView({ activeOrg }: Props) {
  const [digests, setDigests] = useState<DigestRecord[]>([]);
  const [loading, setLoading] = useState(true);
  const [selected, setSelected] = useState<DigestRecord | null>(null);

  useEffect(() => {
    setLoading(true);
    invoke<DigestRecord[]>("get_digests", {
      org: activeOrg === "all" ? null : activeOrg,
    })
      .then(setDigests)
      .finally(() => setLoading(false));
  }, [activeOrg]);

  if (loading) {
    return (
      <div className="p-6">
        <SkeletonBlock />
      </div>
    );
  }

  return (
    <div className="flex flex-1 overflow-hidden">
      <div className="w-64 border-r border-gray-800 overflow-y-auto">
        {digests.length === 0 ? (
          <div className="p-4">
            <p className="text-sm text-gray-600">No digests yet.</p>
            <p className="text-xs text-gray-600 mt-2">
              Digests are generated by the AI layer and saved to{" "}
              <code className="text-gray-500">~/devlog/digests/</code>
            </p>
          </div>
        ) : (
          digests.map((d) => (
            <button
              key={d.id}
              onClick={() => setSelected(d)}
              className={`w-full text-left px-4 py-3 border-b border-gray-800/50 hover:bg-gray-800/50 ${
                selected?.id === d.id ? "bg-gray-800" : ""
              }`}
            >
              <p className="text-sm text-gray-300">{d.period_start} – {d.period_end}</p>
              <p className="text-xs text-gray-600">{d.digest_type}{d.entry_count != null ? ` · ${d.entry_count} entries` : ""}</p>
            </button>
          ))
        )}
      </div>

      <div className="flex-1 overflow-y-auto p-6">
        {selected ? (
          <pre className="text-sm text-gray-400 whitespace-pre-wrap leading-relaxed">
            {selected.content}
          </pre>
        ) : (
          <p className="text-sm text-gray-600">Select a report to view.</p>
        )}
      </div>
    </div>
  );
}
