blank_issues_enabled: false
contact_links:
  - name: Question or discussion
    url: https://github.com/fetchflow/nichinichi/discussions
    about: Use Discussions for questions, ideas, and general conversation
